---
title: "CaseStudy2"
author: "Satvik"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
# employee.data = read.csv("Data/CaseStudy2-data.csv", header = TRUE)
emp.data = read.csv("Data/CaseStudy2-data.csv", header = TRUE)
# Convert columns to factor
cols <- c("JobSatisfaction","Education", "EnvironmentSatisfaction", "JobInvolvement", "JobLevel","PerformanceRating","RelationshipSatisfaction", "WorkLifeBalance","BusinessTravel","StockOptionLevel")
emp.data[cols] <- lapply(emp.data[cols], factor)  ## as.factor() could also be used
sapply(emp.data, class)

#check for missing values
library(naniar)
gg_miss_var(employee.data)
#no missing values in employee.data
sapply(employee.data, function(x) sum(is.na(x)))
```

```{r}
#Convert Columns to facor
summary(employee.data)
no.attrition = emp.data %>% filter(Attrition == "No")

str(no.attrition)
yes.attrition = emp.data %>% filter(Attrition == "Yes")
str(yes.attrition)

```

```{r}
yes.attrition %>% ggplot(aes(x = Age)) + geom_histogram()
no.attrition %>% ggplot(aes(x = Age)) + geom_histogram()
```


```{r}
yes.attrition %>% ggplot(aes(x = Department)) + geom_bar()
no.attrition %>% ggplot(aes(x = Department)) + geom_bar()
```

```{r}
# no.attrition %>% ggplot(aes(x = Department)) + geom_bar(fill=no.attrition$Department)
# no.attrition %>% ggplot(mapping = aes(x = Department, y = ..prop.., group = 1)) + geom_bar(fill = Department)
# yes.attrition %>% ggplot(mapping = aes(x = Department, y = ..prop.., group = 1)) + geom_bar()
```



```{r}
employee.data[employee.data$Attrition == "Yes",] %>% ggplot(aes(x=Department)) + geom_bar()
```

```{r}

```


```{r}
#convert job satisfaction to a factor and get bar plot, use percent 

emp.data %>% ggplot(aes(x = employee.data$JobSatisfaction)) + geom_bar()


yes.attrition %>% ggplot(aes(x = as.factor(JobSatisfaction), fill = as.factor(JobSatisfaction), y=..prop.., group = 1)) + geom_bar() + ggtitle("Attrition")

# yes.attrition %>% ggplot(aes(x = JobSatisfaction, fill = factor(..x..), y=..prop.., group = 1)) + geom_bar() + ggtitle("Yes Attrition") + geom_text(aes( label = scales::percent(..prop..),y= ..prop.. ), stat= "count", vjust = -.5) + scale_y_continuous(labels = scales::percent) + labs(y = "Percent", fill="Satisfaction Level", x = "Job Satisfaction")
# 
# no.attrition %>% ggplot(aes(x = JobSatisfaction, fill = factor(..x..), y=..prop.., group = 1)) + geom_bar() + ggtitle("No Attrition") + geom_text(aes( label = scales::percent(..prop..),y= ..prop.. ), stat= "count", vjust = -.5) + scale_y_continuous(labels = scales::percent) + labs(y = "Percent", fill="Satisfaction Level", x = "Job Satisfaction")

no.attrition %>% ggplot(aes(x = BusinessTravel, fill = factor(..x..), y=..prop.., group = 1)) + geom_bar() + ggtitle("No Attrition") + geom_text(aes( label = scales::percent(..prop..),y= ..prop.. ), stat= "count", vjust = -.5) + scale_y_continuous(labels = scales::percent) + labs(y = "Percent", fill="BusinessTravel", x = "Job Satisfaction")

yes.attrition %>% ggplot(aes(x = BusinessTravel, fill = factor(..x..), y=..prop.., group = 1)) + geom_bar() + ggtitle("No Attrition") + geom_text(aes( label = scales::percent(..prop..),y= ..prop.. ), stat= "count", vjust = -.5) + scale_y_continuous(labels = scales::percent) + labs(y = "Percent", fill="BusinessTravel", x = "Job Satisfaction")

#67% of those that left due to attrition travel rarely
yes.attrition %>% group_by(BusinessTravel) %>%
  summarise(
    count = n(),
    mean = mean(MonthlyRate, na.rm = TRUE),
    sd = sd(MonthlyRate, na.rm = TRUE),
    median = median(MonthlyRate, na.rm = TRUE),
    IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

no.attrition %>% ggplot(aes(x = BusinessTravel, fill = BusinessTravel)) + geom_bar() + ggtitle("No Attrition")
yes.attrition %>% ggplot(aes(x = BusinessTravel, fill = BusinessTravel)) + geom_bar() + ggtitle("Yes Attrition")


```

```{r}
ggplot(data = employee.data, aes(x=DailyRate)) +
geom_histogram(aes(fill=JobSatisfaction)) +
facet_wrap( ~ JobSatisfaction, ncol=2) +
theme_bw()


ggplot(data = employee.data, aes(x=HourlyRate)) +
geom_histogram(aes(fill=JobSatisfaction)) +
facet_wrap( ~ JobSatisfaction, ncol=2) +
theme_bw()

ggplot(data = employee.data, aes(x=MonthlyRate)) +
geom_histogram(aes(fill=JobSatisfaction)) +
facet_wrap( ~ JobSatisfaction, ncol=2) +
theme_bw()

ggplot(data = employee.data, aes(x=MonthlyIncome)) +
geom_histogram(aes(fill=JobSatisfaction)) +
facet_wrap( ~ JobSatisfaction, ncol=2) +
theme_bw()

ggplot(data = employee.data, aes(sample=MonthlyIncome)) +
stat_qq() +
facet_wrap( ~ JobSatisfaction, ncol=1) +
theme_bw()
```


```{r}
fit = aov(MonthlyIncome ~ JobRole, data = emp.data)
summary(fit)
fit1 = aov(MonthlyIncome ~ JobRole, data = yes.attrition)
summary(fit1)


##***## 
##**## Job Satisfaction - HourlyRate
emp.data %>% group_by(MonthlyIncome) %>%
  summarise(
    count = n(),
    mean = mean(MonthlyIncome, na.rm = TRUE),
    sd = sd(MonthlyIncome, na.rm = TRUE),
    median = median(MonthlyIncome, na.rm = TRUE),
    IQR = IQR(MonthlyIncome, na.rm = TRUE)
  )
##***##

library(onewaytests)

library(lsmeans)
#*******************SIGNIFICANT****************#
#Contrast 1
fit4 = lm(MonthlyIncome ~ JobRole, data = employee.data)
summary(fit4)
fit4

leastsquare = lsmeans(fit4,"JobSatisfaction")

Contrasts = list(OneTwoVersusThreeFour= c(0.5,0.5,-0.5,-0.5))

contrast(leastsquare,Contrasts)

#Contrast 2
fit4 = lm(HourlyRate ~ JobSatisfaction, data = employee.data)
summary(fit4)
fit4

leastsquare = lsmeans(fit4,"JobSatisfaction")

Contrasts = list(OneTwoVersusThreeFour= c(1,0,-0.5,-0.5))
#Contrasts = list(OneTwoVersusThreeFour= c(1,0,0,-1))
#Contrasts = list(OneTwoVersusThreeFour= c(1,0,0,-1))
contrast(leastsquare,Contrasts)




bf.test(HourlyRate ~ JobSatisfaction, data = employee.data)
welch.test(HourlyRate ~ JobSatisfaction, data = employee.data)


#Job Satisfaction - DailyRate
employee.data %>% group_by(JobSatisfaction) %>%
  summarise(
    count = n(),
    mean = mean(DailyRate, na.rm = TRUE),
    sd = sd(DailyRate, na.rm = TRUE),
    median = median(DailyRate, na.rm = TRUE),
    IQR = IQR(DailyRate, na.rm = TRUE)
  )


fit1 = aov(DailyRate~JobSatisfaction, data = employee.data)
summary(fit1)

#Job Satisfaction - MonthlyRate
employee.data %>% group_by(JobSatisfaction) %>%
  summarise(
    count = n(),
    mean = mean(MonthlyRate, na.rm = TRUE),
    sd = sd(MonthlyRate, na.rm = TRUE),
    median = median(MonthlyRate, na.rm = TRUE),
    IQR = IQR(MonthlyRate, na.rm = TRUE)
  )


fit2 = aov(MonthlyRate~JobSatisfaction, data = employee.data)
summary(fit2)

#Job Satisfaction - MonthlyIncome
employee.data %>% group_by(JobSatisfaction) %>%
  summarise(
    count = n(),
    mean = mean(MonthlyIncome, na.rm = TRUE),
    sd = sd(MonthlyIncome, na.rm = TRUE),
    median = median(MonthlyIncome, na.rm = TRUE),
    IQR = IQR(MonthlyIncome, na.rm = TRUE)
  )


bf.test(MonthlyIncome ~ JobSatisfaction, data = employee.data)
fit3 = aov(MonthlyIncome~JobSatisfaction, data = employee.data)
summary(fit3)
kruskal.test(MonthlyIncome ~ JobSatisfaction, data=employee.data)




bf.test(DailyRate ~ JobSatisfaction, data = employee.data)
welch.test(DailyRate ~ JobSatisfaction, data = employee.data)

bf.test(MonthlyIncome ~ JobSatisfaction, data = employee.data)
aov(MonthlyIncome ~ JobSatisfaction, data = employee.data)
welch.test(MonthlyIncome ~ JobSatisfaction, data = employee.data)

group_by(employee.data$JobSatisfaction) %>% summarize(meanAge = count(DailyRate))

```


```{r}
#NO ATTRITION

no.attrition %>% group_by(JobSatisfaction) %>%
  summarise(
    count = n(),
    mean = mean(MonthlyRate, na.rm = TRUE),
    sd = sd(MonthlyRate, na.rm = TRUE),
    median = median(MonthlyRate, na.rm = TRUE),
    IQR = IQR(MonthlyRate, na.rm = TRUE)
  )




fitno0 = aov(MonthlyRate~JobSatisfaction, data = no.attrition)
summary(fitno0)
fitno0
```

```{r}
#Yes Attrition
# yes.attrition ~ Jobsatisfaction
yes.attrition %>% group_by(JobSatisfaction) %>%
  summarise(
    count = n(),
    mean = mean(HourlyRate, na.rm = TRUE),
    sd = sd(HourlyRate, na.rm = TRUE),
    median = median(HourlyRate, na.rm = TRUE),
    IQR = IQR(HourlyRate, na.rm = TRUE)
  )
#not enough evidence
fityes = aov(HourlyRate~JobSatisfaction, data = yes.attrition)
summary(fityes)

# yes.attrition ~ Jobsatisfaction


#************Significant****************#

ggplot(data = yes.attrition, aes(x=MonthlyRate)) +
geom_histogram(aes(fill=JobSatisfaction)) +
facet_wrap( ~ JobSatisfaction, ncol=2) +
theme_bw()

yes.attrition %>% group_by(JobSatisfaction) %>%
  summarise(
    count = n(),
    mean = mean(MonthlyRate, na.rm = TRUE),
    sd = sd(MonthlyRate, na.rm = TRUE),
    median = median(MonthlyRate, na.rm = TRUE),
    IQR = IQR(MonthlyRate, na.rm = TRUE)
  )
hist(yes.attrition$MonthlyRate)



fityes0 = aov(MonthlyRate~JobSatisfaction, data = yes.attrition)
summary(fityes0)
fityes0

leastsquare = lsmeans(fityes0,"JobSatisfaction")

#Contrasts = list(AverageOneTwoVersusAverageThreeFour= c(0.5,0.5,-0.5,-0.5))
#contrast(leastsquare,Contrasts)

# Contrast2 = list(OneVersusAverageThreeFour= c(1,0,-0.5,-0.5))
# contrast(leastsquare,Contrast2)

# Contrast3 = list(OneVersusAverageTwoThreeFour= c(3,-1,-1,-1))
# contrast(leastsquare,Contrast3)

#Contrasts = list(OneTwoVersusThreeFour= c(1,0,0,-1))


#***************************#




#DailyRate
yes.attrition %>% group_by(JobSatisfaction) %>%
  summarise(
    count = n(),
    mean = mean(DailyRate, na.rm = TRUE),
    sd = sd(DailyRate, na.rm = TRUE),
    median = median(DailyRate, na.rm = TRUE),
    IQR = IQR(DailyRate, na.rm = TRUE)
  )



fityes1 = aov(DailyRate~JobSatisfaction, data = yes.attrition)
summary(fityes1)


#MonthlyIncome
yes.attrition %>% group_by(JobSatisfaction) %>%
  summarise(
    count = n(),
    mean = mean(MonthlyIncome, na.rm = TRUE),
    sd = sd(MonthlyIncome, na.rm = TRUE),
    median = median(MonthlyIncome, na.rm = TRUE),
    IQR = IQR(MonthlyIncome, na.rm = TRUE)
  )



fityes2 = aov(MonthlyIncome~JobSatisfaction, data = yes.attrition)
summary(fityes2)


fityes3 = aov(MonthlyIncome~JobSatisfaction, data = yes.attrition)
summary(fityes2)

#MonthlyRate
```

```{r}
yes.attrition %>% ggplot(aes(x = as.factor(yes.attrition$YearsSinceLastPromotion))) + geom_bar()
no.attrition %>% ggplot(aes(x = as.factor(no.attrition$YearsSinceLastPromotion))) + geom_bar()

yes.attrition %>% ggplot(aes(x = as.factor(YearsSinceLastPromotion), fill = factor(..x..), y=..prop.., group = 1)) + geom_bar() + ggtitle("Yes Attrition") + geom_text(aes( label = scales::percent(..prop..),y= ..prop.. ), stat= "count", vjust = -.5) + scale_y_continuous(labels = scales::percent) + labs(y = "Percent", fill="Years", x = "YearsSinceLastPromotion")


employee.data %>% group_by(YearsSinceLastPromotion) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

yes.attrition %>% group_by(YearsSinceLastPromotion) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

no.attrition %>% group_by(YearsSinceLastPromotion) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

yes.attrition %>% group_by(JobInvolvement) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

no.attrition %>% group_by(JobInvolvement) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )


no.attrition %>% group_by(EducationField) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

#Life sciences and medical field composed of over half the people that left. (53+37)/140

no.attrition %>% group_by(EducationField) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )


yes.attrition %>% group_by(EducationField) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

#high turnover in the research&development and sales department

yes.attrition %>% group_by(Department) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

no.attrition %>% group_by(Department) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )


no.attrition %>% group_by(EnvironmentSatisfaction) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

yes.attrition %>% group_by(EnvironmentSatisfaction) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

#*****#

no.attrition %>% group_by(JobRole) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

yes.attrition %>% group_by(JobRole) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )


sales.rep.no = no.attrition %>% filter(JobRole == "Sales Representative")
sales.rep.yes = yes.attrition %>% filter(JobRole == "Sales Representative")


sales.rep.yes %>% group_by(EducationField) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )



sales.rep.yes %>% group_by(TrainingTimesLastYear) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )

sales.rep.no %>% group_by(TrainingTimesLastYear) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )
sales.rep.no %>% group_by(YearsInCurrentRole) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )


yes.attrition %>% group_by(YearsInCurrentRole) %>%
  summarise(
    count = n(),
    # mean = mean(MonthlyRate, na.rm = TRUE),
    # sd = sd(MonthlyRate, na.rm = TRUE),
    # median = median(MonthlyRate, na.rm = TRUE),
    # IQR = IQR(MonthlyRate, na.rm = TRUE)
  )


no.attrition %>% ggplot(aes(x = as.factor(YearsSinceLastPromotion), fill = factor(..x..), y=..prop.., group = 1)) + geom_bar() + ggtitle("No Attrition") + geom_text(aes( label = scales::percent(..prop..),y= ..prop.. ), stat= "count", vjust = -.5) + scale_y_continuous(labels = scales::percent) + labs(y = "Percent", fill="Years", x = "YearsSinceLastPromotion")

```




```{r}
#Part 2

str(employee.data)

emp.data = read.csv("Data/CaseStudy2-data.csv", header = TRUE)

# Convert columns to factor
cols <- c("JobSatisfaction","Education", "EnvironmentSatisfaction", "JobInvolvement", "JobLevel","PerformanceRating","RelationshipSatisfaction", "WorkLifeBalance","BusinessTravel","StockOptionLevel")
emp.data[cols] <- lapply(emp.data[cols], factor)  ## as.factor() could also be used
sapply(emp.data, class)

emp.data %>% ggplot(aes(x = Age, y = HourlyRate,color = Attrition)) + geom_point()

train %>% ggplot(aes(x = Age, y = MonthlyIncome,color = Attrition)) + geom_point()
train %>% ggplot(aes(x = Age, y = MonthlyRate,color = Attrition)) + geom_point()
train %>% ggplot(aes(x = Age, y = HourlyRate,color = Attrition)) + geom_point()
train %>% ggplot(aes(x = Age, y = DailyRate,color = Attrition)) + geom_point()
train %>% ggplot(aes(x = HourlyRate, y = DailyRate,color = Attrition)) + geom_point()
train %>% ggplot(aes(x = HourlyRate, y = MonthlyRate,color = Attrition)) + geom_point()
#***#
train %>% ggplot(aes(x = HourlyRate, y = MonthlyIncome,color = Attrition)) + geom_point()
train %>% ggplot(aes(x = MonthlyRate, y = MonthlyIncome,color = Attrition)) + geom_point()
train %>% ggplot(aes(x = MonthlyRate, y = DailyRate,color = Attrition)) + geom_point()




splitPerc = .70
trainIndices = sample(1:dim(emp.data)[1],round(splitPerc * dim(emp.data)[1]))
train = emp.data[trainIndices,]
test = emp.data[-trainIndices,]
#Age and Stock Option
classifications = knn(train[,c(2,29)],test[,c(2,29)],train$Attrition, prob = TRUE, k = 9)
table(classifications,test$Attrition)
confusionMatrix(table(classifications,test$Attrition))
#Stock Option and Job Role
classifications = knn(train[,c(17,29, 6)],test[,c(17,29,6)],train$Attrition, prob = TRUE, k = 4)
table(classifications,test$Attrition)
confusionMatrix(table(classifications,test$Attrition))
colnames(train)

classifications = knn(train[,c(17,29,33)],test[,c(17,29,33)],train$Attrition, prob = TRUE, k = 3)
table(classifications,test$Attrition)
confusionMatrix(table(classifications,test$Attrition))

colnames(train)

iterations = 100
masterAcc = matrix(nrow = iterations)
masterSen = matrix(nrow = iterations)
masterSpe = matrix(nrow = iterations)
splitPerc = .70 #Training / Test split Percentage

for(j in 1:iterations)
{
  
  trainIndices = sample(1:dim(emp.data)[1],round(splitPerc * dim(emp.data)[1]))
  train = emp.data[trainIndices,]
  test = emp.data[-trainIndices,]
  model = naiveBayes(train[,c(2,4,5,9,12,14,15,16,17,20,22,24,25,29,30,31,32,33,34,36)],train$Attrition)
  table(predict(model,test[,c(2,4,5,9,12,14,15,16,17,20,22,24,25,29,30,31,32,33,34,36)]),test$Attrition)
  CM = confusionMatrix(table(predict(model,test[,c(2,4,5,9,12,14,15,16,17,20,22,24,25,29,30,31,32,33,34,36)]),test$Attrition))
  masterAcc[j] = CM$overall[1]
  masterSen[j] = CM$byClass["Sensitivity"]
  masterSpe[j] = CM$byClass["Specificity"]

}

MeanAcc = colMeans(masterAcc)
MeanSen = colMeans(masterSen)
MeanSpe = colMeans(masterSpe)
MeanAcc
MeanSen
MeanSpe
#16,17,20,22,24,25,29,30,31,32,33,34
#DailyRate 5
#HourlyRate 14
#MonthlyIncome 20****
#MonthlyRate 21
train[,c(2,4:5,9,12,14:17)]
colnames(train[,c(2,4:5,9,12,14:17)])
test[,c(2,4,5,7,8,9,12,13, 14, 16, 17,20,21,22,24,25,29,30,31,32,33,34)]
#Set Seed test
splitPerc = 0.7
trainIndices = sample(1:dim(emp.data)[1],round(splitPerc * dim(emp.data)[1]))
train = emp.data[trainIndices,]
test = emp.data[-trainIndices,]
#Age, HourlyRate, JobRole, MonthlyIncome, StockOptionLevel, YearsInCurrentRole, TotalWorkingYears
model = naiveBayes(train[,c(2,14,17,20,29, 30,34)],train$Attrition)
table(predict(model,test[,c(2,14,17,20,29,30,34)]),test$Attrition)
confusionMatrix(table(predict(model,test[,c(2,14,17,20,29,30,34)]),test$Attrition))



#**** above .60 in Sensitivity and Specificity
splitPerc = 0.70
trainIndices = sample(1:dim(emp.data)[1],round(splitPerc * dim(emp.data)[1]))
train = emp.data[trainIndices,]
test = emp.data[-trainIndices,]
model12 = naiveBayes(train[,c(2,4,5,9,12,14,15,16,17,20,22,24,25,29,30,31,32,33,34,36)],train$Attrition)
table(predict(model12,test[,c(2,4,5,9,12,14,15,16,17,20,22,24,25,29,30,31,32,33,34,36)]),test$Attrition)
confusionMatrix(table(predict(model12,test[,c(2,4,5,9,12,14,15,16,17,20,22,24,25,29,30,31,32,33,34,36)]),test$Attrition))
model12_preds=predict(model12, newdata = case2.no.attrition)
as.data.frame(model12_preds)



# my_submissionA <- data_frame('ID' = test$Id, 'SalePrice' = predicted_prices)

case2.no.attrition = read.csv("Data/CaseStudy2CompSet No Attrition.csv", header = TRUE)

cols <- c("JobSatisfaction", "Education", "EnvironmentSatisfaction", "JobInvolvement", "JobLevel","PerformanceRating","RelationshipSatisfaction", "WorkLifeBalance","BusinessTravel","StockOptionLevel")
case2.no.attrition[cols] <- lapply(case2.no.attrition[cols], factor)  ## as.factor() could also be used
sapply(case2.no.attrition, class)

case2.no.attrition
library(class)
library(caret)
library(e1071)




```



```{r}
#Part 3
newemp.data = read.csv("Data/CaseStudy2-data.csv", header = TRUE)
# Convert columns to factor
cols <- c("JobSatisfaction","Education", "EnvironmentSatisfaction", "JobInvolvement", "JobLevel","PerformanceRating","RelationshipSatisfaction", "WorkLifeBalance","BusinessTravel","StockOptionLevel")
newemp.data[cols] <- lapply(newemp.data[cols], factor)  ## as.factor() could also be used
sapply(newemp.data, class)

newemp.data$Over18 = NULL

case2.no.salary = read.csv("Data/CaseStudy2CompSet No Salary.csv", header=TRUE)
cols <- c("JobSatisfaction", "Education", "EnvironmentSatisfaction", "JobInvolvement", "JobLevel","PerformanceRating","RelationshipSatisfaction","WorkLifeBalance","BusinessTravel","StockOptionLevel")

case2.no.salary[cols] <- lapply(case2.no.salary[cols], factor)  ## as.factor() could also be used
sapply(case2.no.salary, class)
plot(tes)

library(olsrr)





```


```{r}
testfit = lm(MonthlyIncome ~ .,data = newemp.data)
plot(testfit)
summary(testfit)
RMSE(testfit)
library(DAAG)
ols_step_backward_p(testfit,prem = 0.05,details = TRUE)
testfit1 = lm(MonthlyIncome ~ TotalWorkingYears*factor(JobLevel)+DailyRate*factor(JobRole),data = newemp.data)
testfit2 = lm(log(MonthlyIncome) ~ TotalWorkingYears*factor(JobRole),data = newemp.data)

summary(testfit1)
plot(testfit1)
press(testfit1)

press(testfit2)
plot(testfit2)
summary(testfit2)
ols_step_forward_p(testfit2)
?cv.lm
#DailyRate 5
#HourlyRate 14
#MonthlyIncome 20****
#MonthlyRate
nemp.data
numMSPEs = 500
#MSPEHolderModel1 = numeric(numMSPEs)
MSPEHolderModel2 = numeric(numMSPEs)

for (i in 1:numMSPEs)
{
  TrainObs = sample(seq(1,dim(newemp.data)[1]),round(.75*dim(newemp.data)[1]),replace = FALSE)
  EmpTrain = newemp.data[TrainObs,]
  EmpTrain
  EmpTest = newemp.data[-TrainObs,]
  EmpTest
  #Model 2
  Model2_fit = lm(log(MonthlyIncome) ~ TotalWorkingYears*factor(JobLevel)+DailyRate*factor(JobRole), data = EmpTrain)
  Model2_Preds = predict(Model2_fit,newdata = EmpTest)
  MSPE = mean((EmpTest$MonthlyIncome - Model2_Preds)^2)
  MSPE
  MSPEHolderModel2[i] = MSPE
  
}

mean(MSPEHolderModel2)

```





